from .veo31_nodes import (
    NODE_CLASS_MAPPINGS as _VEO_CLASSES,
    NODE_DISPLAY_NAME_MAPPINGS as _VEO_NAMES,
)
from .veo31_video_saver import (
    NODE_CLASS_MAPPINGS as _SAVER_CLASSES,
    NODE_DISPLAY_NAME_MAPPINGS as _SAVER_NAMES,
)

NODE_CLASS_MAPPINGS        = {**_VEO_CLASSES, **_SAVER_CLASSES}
NODE_DISPLAY_NAME_MAPPINGS = {**_VEO_NAMES,   **_SAVER_NAMES}

__all__ = ["NODE_CLASS_MAPPINGS", "NODE_DISPLAY_NAME_MAPPINGS"]
